/*
  Even Fibonacci numbers
  Problem 2
  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int main() {
    int i = 1;
    int j = 2;
    int temp = 0;
    int sum = 0;
    while (j <= 4000000) {
        if (j % 2 == 0) {
            sum += j;
        }
        temp = i;
        i = j;
        j = temp + j;
    }
    cout << sum << endl;
    return 0;
}
